### ISSUE TITLE
Queue "wildebeest" does not exist. To create it, run: wrangler queues create wildebeest

### ISSUE THREAD

**Issue by thepatrick** [cloudflare/wildebeest#101]
I see #100 was merged which does this, but that doesn't get run (`Publish consumer` fails with the `Queue "wildebeest" does not exist. To create it, run: wrangler queues create wildebeest`)

**Comment by thepatrick** [comment]
I manually created the queue which got past this - but that required enabling the Queues beta, which requires a paid Workers plan too (something to update in the readme)

**Comment by xtuc** [comment]
fixed https://github.com/cloudflare/wildebeest/commit/95385a429659ea0ca5d36386439caebeadd79ffc

**Comment by dferber90** [comment]
I ran into the same problem today after the fix was merged https://github.com/dferber90/wildebeest/actions/runs/3917981237/jobs/6698102070#step:24:73

I had not enabled queues on my account yet which I believe caused this. Would be good to have "Enable Queues" as part of the setup instructions
