### ISSUE TITLE
GitHub Actions are enabled on my Fork, but Deploy to CloudFlare Workers can't see it

### ISSUE THREAD

**Issue by TedTschopp** [cloudflare/wildebeest#103]
I don't really know where to leave feedback, so I'm doing this here.  I can get all the way to the step where I enable GitHub Actions on my forked repo in Github (https://github.com/TedTschopp/wildebeest) but the Deploy to Cloudflare Workers screen is not seeing it as shown by this screenshot below.   I don't know if the issue is with GitHub (I don't think so), or with Wildebeest (maybe) or with CloudFlare Workers not being able to read the state of Github (I'm guessing this one, but I don't know how to debug further).

<img width="759" alt="Screenshot 2023-01-13 at 9 17 58 AM" src="https://user-images.githubusercontent.com/709984/212380361-57bbb0ff-3a02-41a1-a170-a20d4dfa64db.png">

**Comment by xtuc** [comment]
Have you tried to click on the "Repository - Actions" link? That should let you enable GitHub actions. Closing the issue but feel free to reopen if needed.
