### ISSUE TITLE
Failure to Deploy `Queue "wildebeest" does not exist.`

### ISSUE THREAD

**Issue by AndyNortrup** [cloudflare/wildebeest#107]
I've been attempting to deploy this in a brand-new environment today (literally created my first cloudflare account today).  While following the instructions I receive this error in the deploy action. 

```
$ Running: wrangler publish --config consumer/wrangler.toml
 ⛅️ wrangler 2.7.1 
-------------------
▲ [WARNING] Processing consumer/wrangler.toml configuration:
    - D1 Bindings are currently in alpha to allow the API to evolve before general availability.
      Please report any issues to https://github.com/cloudflare/wrangler2/issues/new/choose
      Note: Run this command with the environment variable NO_D1_WARNING=true to hide this message
  
      For example: `export NO_D1_WARNING=true && wrangler <YOUR COMMAND HERE>`
Your worker has access to the following bindings:
- KV Namespaces:
  - KV_CACHE: a9e08b35f37d4d26b92f6b35b9bd6100
- D1 Databases:
  - DATABASE: wildebeest-andynortrup (b3a42301-d8f5-4d2b-822b-28c546bd459f)
- Vars:
  - DOMAIN: "social.nortrup.dev"
  - ADMIN_EMAIL: "andy@nortrup.dev"
Total Upload: 56.19 KiB / gzip: 13.18 KiB
✘ [ERROR] Queue "wildebeest" does not exist. To create it, run: wrangler queues create wildebeest
If you think this is a bug then please create an issue at https://github.com/cloudflare/wrangler2/issues/new/choose
##[debug]Docker Action run completed with exit code 1
##[debug]Finishing: Publish consumer
```

Full run: https://github.com/AndyNortrup/wildebeest/actions/runs/3920800870

I've double checked that I should have all of the permissions required for the API key. 

Thank you in advance, this is an exciting project.

**Comment by elitepleb** [comment]
it requires the pay as you go version of workers, which makes this an existential nightmare for anyone to run
https://github.com/cloudflare/wildebeest/pull/104

even once deployed, it kept on erroring out with no clear way to debug it

better to skip it for another few months, even if it worked, you'd hit the 100mb D1 limit quickly

**Comment by AndyNortrup** [comment]
I'm intending to use this as a single person instance, I think I'll be alright. But I'll turn on some spend alerts.

**Comment by AndyNortrup** [comment]
As stated by @elitepleb adding the paid workers plan to be able to use queues resolved the issue. 

Duplicate of #104
