### ISSUE TITLE
Deploy process does not create a Cloudflare Pages project

### ISSUE THREAD

**Issue by AndyNortrup** [cloudflare/wildebeest#140]
The step [Add Queue to Producer Pages](https://github.com/cloudflare/wildebeest/blob/346b0a19dcd3bc7e00db67a6ead9ff65e2f52692/.github/workflows/deploy.yml#L258) in Deploy.yml makes a call to the `PATCH` endpoint of the cloudflare pages API.  This will update the project if it exists, but will fail on first run if the project doesn't exist.  I was able to work around this by executing this command from my terminal then running the workflow again.  

Ideally the workflow should check if the workflow exists and create it if it's missing OR update an existing project: 

```
curl https://api.cloudflare.com/client/v4/accounts/***/pages/projects/ \                                            
      -X POST \
      -H 'Authorization: Bearer ***' \
      -d  '{ "name": "wildebeest-<username>", "production_branch": "main",
          "deployment_configs": {
            "production": {
              "queue_producers": {
                "QUEUE": {
                  "name": "wildebeest"
                }
              }
            }
          }
        }'
```

**Comment by xtuc** [comment]
Could you please check what the Configure step says?

**Comment by AndyNortrup** [comment]
> Could you please check what the Configure step says?

I have checked the configuration step. I does a PATCH operation which only updates an existing project but won't create a pages project. The patch doesn't function as an upsert. 

I just reread the installation instructions and there are no mentions of configuring pages manually.

**Comment by AndyNortrup** [comment]
Coming back to this.  I now see the configuration of the pages in the Configure step. However, in looking back through all of my runs if the configure step fails, then the workflow continues. In my case this caused errors later in the process when services were not configured or available.  

* https://github.com/AndyNortrup/wildebeest/actions/runs/3952356179/jobs/6768338945#step:19:200
* https://github.com/AndyNortrup/wildebeest/actions/runs/3920340829/jobs/6701925926#step:18:193
* https://github.com/AndyNortrup/wildebeest/actions/runs/3920800870/jobs/6703944325#step:18:193

I see that `continue-on-error: true` is set for the Deploy step.  which seems like it would contribute to that behavior.

**Comment by xtuc** [comment]
`continue-on-error: true` has been removed since.

From the logs, it looks like Cloudflare Access is missing. Please enable the product and rerun. Feel free to reopen the issue if the error persists.
