### ISSUE TITLE
D1 database migration error when running initial deploy GitHub action

### ISSUE THREAD

**Issue by josephschmitt** [cloudflare/wildebeest#156]
While trying to "Deploy with Workers" for the first time, my fork's GitHub action fails on the `migrate D1 database` step with the [following error](https://github.com/josephschmitt/wildebeest/actions/runs/3990565672/jobs/6844360751): <pre>[ERROR] Can't find a DB with name/binding 'wildebeest-josephschmitt' in local config. Check info in wrangler.toml...</pre>

<details>
<summary>Full stack trace</summary>

```
/usr/bin/docker run --name ea425b5ca650dc10fd4bd6a7383f6798398dcf_c2bf12 --label ea425b --workdir /github/workspace --rm -e "OWNER_LOWER" -e "TERRAFORM_CLI_PATH" -e "CLOUDFLARE_ACCOUNT_ID" -e "INPUT_COMMAND" -e "INPUT_APITOKEN" -e "INPUT_PRECOMMANDS" -e "INPUT_APIKEY" -e "INPUT_EMAIL" -e "INPUT_ACCOUNTID" -e "INPUT_ENVIRONMENT" -e "INPUT_WORKINGDIRECTORY" -e "INPUT_WRANGLERVERSION" -e "INPUT_SECRETS" -e "INPUT_POSTCOMMANDS" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/wildebeest/wildebeest":"/github/workspace" ea425b:5ca650dc10fd4bd6a7383f6798398dcf
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead

added 101 packages, and audited 102 packages in 2s

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Using API Token authentication
$ Running: echo "*** pre commands ***"
echo -e "[[d1_databases]]\nbinding=\"DATABASE\"\ndatabase_name=\"wildebeest-josephschmitt\"\ndatabase_id=\"\"" >> wrangler.toml
echo "******"

*** pre commands ***
******
$ Running: wrangler d1 migrations apply wildebeest-josephschmitt
▲ [WARNING] Processing wrangler.toml configuration:

    - D1 Bindings are currently in alpha to allow the API to evolve before general availability.
      Please report any issues to https://github.com/cloudflare/wrangler2/issues/new/choose
      Note: Run this command with the environment variable NO_D1_WARNING=true to hide this message
  
      For example: `export NO_D1_WARNING=true && wrangler <YOUR COMMAND HERE>`
--------------------
    - D1 Bindings are currently in alpha to allow the API to evolve before general availability.
      Please report any issues to https://github.com/cloudflare/wrangler2/issues/new/choose
      Note: Run this command with the environment variable NO_D1_WARNING=true to hide this message
  
      For example: `export NO_D1_WARNING=true && wrangler <YOUR COMMAND HERE>`


🚧 D1 is currently in open alpha and is not recommended for production data and traffic
🚧 Please report any bugs to https://github.com/cloudflare/wrangler2/issues/new/choose
🚧 To request features, visit https://community.cloudflare.com/c/developers/d1
🚧 To give feedback, visit https://discord.gg/cloudflaredev
--------------------


✘ [ERROR] Can't find a DB with name/binding 'wildebeest-josephschmitt' in local config. Check info in wrangler.toml...
```
</details>

Is there a step that I'm missing other than what's described in the README? As far as I know I've done everything in there, and I don't see any instructions on customizing the `wrangler.toml` file.

**Comment by xtuc** [comment]
It looks like the D1 database failed to create. Could  you please look at the `Create D1 database` step?

**Comment by josephschmitt** [comment]
Aha, you're right, that step shows an error. It didn't fail the actual step, though, so it looked like it was succesful. I'm guessing the script is swallowing the exit code. Would be good to have that step actually fail. Thanks!

**Comment by josephschmitt** [comment]
@xtuc Related: it failed because of authentication issues, which I'm not surprised because I had no idea what permissions to set when generating the API key as the README didn't have any guidance. Do you have any docs I can look at to see what permissions are needed?

**Comment by xtuc** [comment]
We changed the step to exit on failure since.

You can create a API token with the correct permissions using this link: https://dash.cloudflare.com/profile/api-tokens?permissionGroupKeys=[{%22key%22:%22d1%22,%22type%22:%22edit%22},{%22key%22:%22page%22,%22type%22:%22edit%22},{%22key%22:%22images%22,%22type%22:%22edit%22},{%22key%22:%22access%22,%22type%22:%22edit%22},{%22key%22:%22workers_kv_storage%22,%22type%22:%22edit%22},{%22key%22:%22access_acct%22,%22type%22:%22read%22},{%22key%22:%22dns%22,%22type%22:%22edit%22},{%22key%22:%22workers_scripts%22,%22type%22:%22edit%22}]&name=Wildebeest.

Feel free to reopen the issue if you need.

**Comment by josephschmitt** [comment]
> We changed the step to exit on failure since.
> 
> You can create a API token with the correct permissions using this link: [https://dash.cloudflare.com/profile/api-tokens?permissionGroupKeys=[{%22key%22:%22d1%22,%22type%22:%22edit%22},{%22key%22:%22page%22,%22type%22:%22edit%22},{%22key%22:%22images%22,%22type%22:%22edit%22},{%22key%22:%22access%22,%22type%22:%22edit%22},{%22key%22:%22workers_kv_storage%22,%22type%22:%22edit%22},{%22key%22:%22access_acct%22,%22type%22:%22read%22},{%22key%22:%22dns%22,%22type%22:%22edit%22},{%22key%22:%22workers_scripts%22,%22type%22:%22edit%22}]&name=Wildebeest](https://dash.cloudflare.com/profile/api-tokens?permissionGroupKeys=%5B%7B%22key%22:%22d1%22,%22type%22:%22edit%22%7D,%7B%22key%22:%22page%22,%22type%22:%22edit%22%7D,%7B%22key%22:%22images%22,%22type%22:%22edit%22%7D,%7B%22key%22:%22access%22,%22type%22:%22edit%22%7D,%7B%22key%22:%22workers_kv_storage%22,%22type%22:%22edit%22%7D,%7B%22key%22:%22access_acct%22,%22type%22:%22read%22%7D,%7B%22key%22:%22dns%22,%22type%22:%22edit%22%7D,%7B%22key%22:%22workers_scripts%22,%22type%22:%22edit%22%7D%5D&name=Wildebeest).
> 
> Feel free to reopen the issue if you need.

Thank you!!!
