### ISSUE TITLE
Catching /api not found

### ISSUE THREAD

**Issue by xmflsct** [cloudflare/wildebeest#165]
Currently when requests going to `/api` that do not match either of [these paths](https://github.com/cloudflare/wildebeest/blob/1033fb18f94afa69e0f80ec92e9b63992ea2f7e1/backend/src/middleware/main.ts#L49-L61), it would be captured by [the frontend](https://github.com/cloudflare/wildebeest/blob/1033fb18f94afa69e0f80ec92e9b63992ea2f7e1/frontend/src/routes/not-found/index.tsx). What is worse is that the frontend not found page's status is 200, confusing the client app of invalid data received.

**Comment by xtuc** [comment]
Currently unknown pathes are being redirected to /not-found. Instead I think we should return a 404 and serve the /not-found frontend page.

**Comment by xmflsct** [comment]
Yep, that is also fine, at least need to fix not found being returned as `200`. Thanks!
