### ISSUE TITLE
D1 Error when Actor is not a Person

### ISSUE THREAD

**Issue by riaf** [cloudflare/wildebeest#178]
I've encountered a D1 Error when the Actor being processed is not a Person.
The issue arises in the `getAndCache` method in `backend/src/activitypub/actors/index.ts` where the cache only retrieves data for Person actors.
If the desired Actor type is a Service, the data is retrieved from the URL and inserted into the actor table, but there is a chance the data has already been inserted which results in a UNIQUE constraint error and throws an exception, preventing proper processing.

To avoid this issue, one potential solution could be to allow the cache to retrieve data for actors other than Person or temporarily use SQL such as `INSERT IGNORE` to suppress the error, but this will significantly slow down the operation as it disables the cache.

I am very excited about this product and apologize for not being able to contribute a Pull Request due to lack of time.

**Comment by xtuc** [comment]
Thanks for the detailed issue! I was actually just fixing that, i'll send a PR.
