### ISSUE TITLE
Support for account migrations

### ISSUE THREAD

**Issue by jonaharagon** [cloudflare/wildebeest#238]
Mastodon supports redirecting profiles and moving your followers between different Mastodon accounts with its account [migrations feature](https://docs.joinmastodon.org/user/moving/#move). Is this something Wildebeest might support in the future?

It doesn't feel realistic for many people to move their Mastodon accounts *to* a personal Wildebeest instance on their own domain, even if Wildebeest allows them to create a personal instance more easily than Mastodon does, because there's no way to bring the following many people already have on Mastodon over here. This is the dealbreaker for me trying out Wildebeest personally anyways. It'd also be nice to support migrating out of Wildebeest in case of a domain change or a need to use ActivityPub software with a different feature-set later on.

**Comment by Keisial** [comment]
While not as obvious as the right to get a copy of your own toots, I think that a broad interpretation of [GDPR Article 20](https://gdpr.eu/article-20-right-to-data-portability/) does imply that the subjects should be able to move their fediverse activity from one ActivityPub provider to another.

Which should include the relatively simple feature of being able to point your followers to the new place, as implemented by most other competitor servers.

**Comment by mkarliner** [comment]
+1
Absolutely

**Comment by xtuc** [comment]
@Keisial  I'm not laywer but I'm guessing GDPR Article 20 doesn't apply to Wildebeest. The data is owned by your account, in your D1 database. You are free to delete / download / move it.

That being said, we don't support Mastodon migrations yet but we are planning to.

**Comment by filipesmedeiros** [comment]
@xtuc amazing to hear. I'd love to migrate into Wildebeest as soon as that's ready 😄

**Comment by alasaarela** [comment]
> That being said, we don't support Mastodon migrations right now but we are planning to.

@xtuc Thanks, I look forward to testing out Wildebeest for our Mastodon server as soon as the migration functionality is in!

**Comment by Keisial** [comment]
@xtuc don't get me wrong, I was thinking on this as an interesting fact. I agree it's not clear it does (thus the _broad interpretation_) but my reading of the GDPR is that it would "want" that you should be able to move your followers as well. Ironically, only because the protocol allows that.
IANAL, so I might be completely wrong as well.

**Comment by japzone1** [comment]
> Migrating from Mastodon to Wildebeest is now possible.

What about the other way around? Can people migrate off of Wildebeest?

**Comment by japzone1** [comment]
> @japzone1 only Mastodon to Wildebeest account migration is supported at the moment.

Why'd you rename and close the issue then? The opening post specifically mentions migration away from Wildebeest as well.

**Comment by xtuc** [comment]
Ah ok, please create a dedicated issue for Wildebeest to Mastodon migration.
