### ISSUE TITLE
Hashtags don’t work in toots

### ISSUE THREAD

**Issue by koehn** [cloudflare/wildebeest#243]
When I post a toot with a #hashtag, I expect it to be correctly tagged and linked. They are not in Wildebeest, neither in Toots originating outside Wildebeest nor from Toots coming from Wildebeest accounts. 

Same is true for hashtags in profiles.

**Comment by xtuc** [comment]
Hashtags aren't implemented yet but we are working on it.

**Comment by xtuc** [comment]
This has been fixed some time ago.
