### ISSUE TITLE
Worker exceeded resource limits

### ISSUE THREAD

**Issue by koehn** [cloudflare/wildebeest#258]
I’m getting an error 1102 when I try to access the site (https://dogwood.social) through my browser. I’m on the unbound plan and cannot find any errors in the dashboard.

**Comment by pisceskaze** [comment]
Have you tries changing on Pages according to the tutorial? 🤔 or any of the Workers?

I have decided to upgrade my Worker to Paid (P.a.y.g) plan, then active Durable object, and it work perfectly now?

**Comment by koehn** [comment]
I should have specified: my app runs, but I’m getting the 1102 intermittently. I have a user set up which is following and followed by other users in the system.

**Comment by celso** [comment]
You probably need Workers Unbound. See:

https://github.com/cloudflare/wildebeest/blob/main/docs/troubleshooting.md#error-1102

And

https://github.com/cloudflare/wildebeest/blob/main/docs/requirements.md

Feel free to reopen if it doesn't solve your issue.
