### ISSUE TITLE
Mobile Navigation Broken

### ISSUE THREAD

**Issue by bretcarmichael** [cloudflare/wildebeest#265]
When viewing a Wildebeest instance on mobile, including https://cloudflare.social/explore/, the menu is outside of the viewport. Pinching the screen forces it to snap inside the viewport.

This seems only to occur on the Explore view, where Local and Federated pages are fine. However, the Explore view is the home view, making navigation not-visible to visitors.

**Comment by dario-piotrowicz** [comment]
Hi @bretcarmichael, I think that the issue was that the dynamic content could push the nav off screen, I've update the styling and it looks much better, thanks for raising it ❤️ 

(PS: please have a look again and let me know if it works fine for you as well 🙂)

**Comment by bretcarmichael** [comment]
Awesome. Thanks, @dario-piotrowicz! I just checked on my phone, and it looks great. 😀

**Comment by dario-piotrowicz** [comment]
@bretcarmichael great to hear! 😃 

thanks for confirming that it's all good now 🙂
