### ISSUE TITLE
Cannot logon with Mastodon mobile client 

### ISSUE THREAD

**Issue by kelsallp** [cloudflare/wildebeest#269]
I created my userid with Pinafore and OAuth.

I have just tried to logon with Mastodon mobile App. The app asks for the server name, and then shows a new user logon screen, rather than a logon screen (OAuth).

**Comment by xtuc** [comment]
Which app are you using?

**Comment by kelsallp** [comment]
It is the Mastodon Android mobile app.

I have just tried it with the Pinafore PWA app in Chrome on Android - same error.

**Comment by kelsallp** [comment]
No it does not work. Here is what I get:

1) Mastodon mobile app loads
2) Mastodon app asks for server name. This wildebeest server name is given, and the app allows this to be selected
3) The Wildebeest Login page is shown (from the page title), but the option to login is not shown, only the option to register
4) If I do actually enter my user name (to register again), then the next screen shows 'Internal Server Error'

**Comment by kelsallp** [comment]
Works now - pops up the CF OAuth logon screen, and goes to a logged-on state after selecting the account.
