### ISSUE TITLE
Feature request: Privacy Policy Page

### ISSUE THREAD

**Issue by nthomasgsy** [cloudflare/wildebeest#281]
Please can I suggest the need to have a privacy policy that is displayed on the root page.  This is required for GDPR compliance in Europe and we are in a grey area of legality without it.  This should be admin editable and if possible should tie in to the Cloudflare cookie policy where Cloudflare services are enabled, such as analytics.

[UK ICO Guidance on how to write a Privacy Notice](https://ico.org.uk/for-organisations/sme-web-hub/how-to-write-a-privacy-notice-and-what-goes-in-it/)

(I had suggested this on Discord server but was told to raise an issue).

**Comment by celso** [comment]
Hi @nthomasgsy, thanks for your message.

The Wildebeast code has been released by Cloudflare under the Apache 2.0 license. You are free to use, modify and deploy the Wildebeast code in accordance with such open source license.

Wildebeast is not provided by Cloudflare as a managed service so we don't have Cloudflare-specific terms or a privacy notice that applies to this open sourced code.

If you choose to deploy the Wildebeast code yourself in Cloudflare Workers using D1, R2, Images or other APIs, your use would be subject to Cloudflare's Terms of Service, Supplemental Terms, and Privacy Notice.

https://www.cloudflare.com/terms/

https://www.cloudflare.com/supplemental-terms/#cloudflare-developer-platform-cloudflare-workers-cloudflare-pages-workers-kv-durable-objects-and-r2

https://www.cloudflare.com/privacypolicy/

You are responsible for including appropriate privacy notices and acceptable use policies for your end users' use of Mastodon.

**Comment by nthomasgsy** [comment]
Hi, to clarify, this is not a request to formulate a policy on my behalf.  But to have a way to provide a link to a static web page from the server home page in the main branch code.  On a similar basis, there should be cookie opt in functionality for those browsing the server homepage.  This is GDPR Privacy By Design and a legal requirement in Europe.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
