### ISSUE TITLE
Load times keep getting longer

### ISSUE THREAD

**Issue by jahanson** [cloudflare/wildebeest#301]
There seems to be an issue with my Wildebeest instance and I'm not sure what could be the culprit. Can anyone provide any advice or where to look?

This is the past week's load times
![image](https://user-images.githubusercontent.com/1548511/219417535-357f26f0-ecf3-4196-af43-3b67317d8491.png)

**Comment by jahanson** [comment]
It's completely unusable now. So I might as well blow it away unless someone from Cloudflare could find some use for it still being up?
![2023-02-20 08_27_24-fedibeest social _ Better Uptime - Brave](https://user-images.githubusercontent.com/1548511/220192910-9792e392-49ae-47b1-a354-2d8063336623.png)

**Comment by geelen** [comment]
You can go ahead and delete it. We're investigating the issue but we have the data we need to track it down, so feel free to clean things up however you like.

**Comment by xtuc** [comment]
We are adding support for other databases, we have an experimental support for https://neon.tech.
