### ISSUE TITLE
Private messages are included on local timeline

### ISSUE THREAD

**Issue by koehn** [cloudflare/wildebeest#303]
1. From the Mastodon client, create a Toot. 
2. Set the audience to “only people I mention” and mention someone, and send the message
3. Go to the main https page for your site (e.g., `https://example.com/explore`) and select “Local” from the list on the right
4. Your private messages are displayed there

**Comment by ThatOneCalculator** [comment]
Lol. Lmao.

**Comment by Sqaaakoi** [comment]
When will the feature be renamed to Public Messages?

**Comment by spacekookie** [comment]
you've got nothing to hide

**Comment by ThatOneCalculator** [comment]
![caption.png](https://user-images.githubusercontent.com/44733677/220763090-fc6fcee6-6dba-4926-8eb3-8d93e39444f0.png)

**Comment by richfelker** [comment]
Has anyone clarified whether this is only visible logged in as yourself (laughably bad ux that could be panic inducing for users, but not actually a privacy leak) or publicly?

**Comment by WesleyAC** [comment]
took a peek at the code and it looks like [there is no attempt at authentication or filtering](https://github.com/cloudflare/wildebeest/blob/7dea01b781a18e7f947c3c2b54b34af3503a4337/backend/src/mastodon/timeline.ts#L124-L144), lol

**Comment by ThatOneCalculator** [comment]
![my-honest-reaction-my-honest-reaction-meme.gif](https://user-images.githubusercontent.com/44733677/220777222-126dd46a-2c53-46ac-b746-5b3730bab03b.gif)

**Comment by WesleyAC** [comment]
it's also real cool and good to assemble the sql statements with string interpolation. afaict that doesn't cause any sql injection problems in the current code, but as soon as there's a path that calls `getObjectBy` with a attacker-controlled `key` or something like that there's gonna be problems.

definitely not a sign of half baked software rushed to ship or anything like that!

**Comment by ThatOneCalculator** [comment]
Is this the part where I start to shill other Fedi software?

**Comment by xtuc** [comment]
Currently private messages are not supported, they will be displayed on the public timeline. I temporarly locked this issue to avoid spam.

**Comment by jae1911** [comment]
The whole fediverse to CF rn:

https://user-images.githubusercontent.com/76598503/220893729-fd200a2a-b54e-4bba-a0be-377c9ab0889e.mp4

**Comment by xtuc** [comment]
Locking the issue permanently.

As I said in https://github.com/cloudflare/wildebeest/issues/303#issuecomment-1440961701. At the moment, private messages are not supported and we are well aware. Our team is looking into it.

Thanks for the issue @koehn. Feel free to reach out to me directly on Discord for concerns / questions.

**Comment by xtuc** [comment]
A fix has been merged. Private messages sent from Wildeebest are not showing in public timelines anymore. Please sync your forks to patch your instance.

Also note that, for safety, toots with private or unlisted visbility are now rejected until we implement them properly.

In the future, issues that could be security related can be reported via https://github.com/cloudflare/wildebeest/blob/main/SECURITY.md.

Closing this since the original issue has been addressed.
