### ISSUE TITLE
If server rule are deleted, rule numbers are not changed

### ISSUE THREAD

**Issue by Lastorder-DC** [cloudflare/wildebeest#376]
![chrome_2023-03-07_10-38-58](https://user-images.githubusercontent.com/18280396/223296956-7aee4f7a-3063-4fc7-9c1a-9ed94a469bd9.png)

1. Add server rule
2. Delete first rule
3. Add another rule
4. First rule's number will be `2`, not `1`

**Comment by dario-piotrowicz** [comment]
dang, sorry I missed that 😓 

thanks a lot for the issue, I'll fix it asap
