### ISSUE TITLE
Redployments should be a no-op 

### ISSUE THREAD

**Issue by petebacondarwin** [cloudflare/wildebeest#40]
When you run the deployment script a second time it will fail because things like the KV store are already created.
We should be resilient to this and just skip those steps.

**Comment by xtuc** [comment]
The terraform state needs to be stored somewhere.

**Comment by veggiedefender** [comment]
s3 terraform backend + r2 on the free tier?

**Comment by xtuc** [comment]
terraform state is now stored in KV.
