### ISSUE TITLE
Redirect all frontend routes to start-instance until configured

### ISSUE THREAD

**Issue by petebacondarwin** [cloudflare/wildebeest#41]

**Comment by xtuc** [comment]
I intentially didn't do it to avoid adding a D1 query on all requests.

**Comment by petebacondarwin** [comment]
But don't we hit D1 on every frontend UI request anyway? Especially now that we are reading the thumbnail etc from the DB?
In the data loader for access the instance-config, we could trigger a redirect if no data is returned.

**Comment by xtuc** [comment]
We would need to query D1 to detect that  the instance hasn't been configured.

**Comment by petebacondarwin** [comment]
This code runs on every frontend request: https://github.com/cloudflare/wildebeest/blob/44898ac86ea2a6ea05919ea55a0ef3733f6bdd52/frontend/src/routes/layout.tsx#L18-L25

In this function, we can check whether the config exists (rather than just naively casting it) and throw a `response.redirect()` to push the user to the `start-instance` page instead.

**Comment by petebacondarwin** [comment]
And if this is problematic (from a performance point of view) we need to implement some caching of the instance data in the system somewhere (outside of D1).
