### ISSUE TITLE
Implement integration frontend tests

### ISSUE THREAD

**Issue by dario-piotrowicz** [cloudflare/wildebeest#47]
currently we have a single integration test for the frontend application:  [frontend/test/post-page.spec.ts](https://github.com/cloudflare/wildebeest/blob/036db19ede388714acb6a6624c08c694849d960a/frontend/test/posts-page.spec.ts)

given the simplicity of the read-only UI we don't need to go overboard and have fully fledged E2E tests, not unit tests are necessary but we should create integration tests such as the `post-page` one mentioned about, we should have one test per page so that we can be confident that things are working acceptably well.

we should also make sure that the left column is tested as well since it is populated by dynamic content provided by the backend

**Comment by xtuc** [comment]
Is this still needed @dario-piotrowicz ?

**Comment by dario-piotrowicz** [comment]
good question :slightly_smiling_face::+1: 

@jculvey you added the tests, are they covering everything we wanted to? should we close this issue as completed?
