### ISSUE TITLE
set descriptive user-agent header for federation

### ISSUE THREAD

**Issue by selfisekai** [cloudflare/wildebeest#80]
implementations typically set descriptive user-agents like `http.rb/5.1.0 (Mastodon/4.0.2; +https://kolektiva.social/)` or `Akkoma 3.5.0-10-gfd2f03f8-develop; https://crimew.gay <plerombo@crimew.gay>`

https://github.com/cloudflare/wildebeest/blob/main/backend/src/activitypub/deliver.ts

**Comment by xtuc** [comment]
That would be ideal. Would you like to send a pull request to add a User-Agent?

**Comment by xtuc** [comment]
Added a user-agent header for inbox delivery.

**Comment by xtuc** [comment]
I'm closing this issue since what you suggested has been implemented. Feel free to reopen if needed.
